version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
            name: Deploy app
            command: ssh -oStrictHostKeyChecking=no -v circleci@jixion.com "sudo ./screen-wrapper-graphql.sh ${NASA} ${OWM}"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main